name: Build Sandbox Container
on:
  push:
  schedule:
   - cron: '12 20 13 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}


jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ubuntuversion: [ '22.04', '23.10', '24.04' ]
    uses: ./.github/workflows/docker_build.yml
    with:
      version: "${{matrix.ubuntuversion}}"
