name: Build Sandbox Container
on:
  push:
  schedule:
   - cron: '12 20 13 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}


jobs:
  build-22_04:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker_build.yml
    with:
      version: "22.04"


  build-23_04:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker_build.yml
    with:
      version: "23.04"
