name: Build Sandbox Container
on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}


jobs:
  build-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

      - name: Clean untagged container versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title']}}
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'

      - name: List versions
        env:
          GH_TOKEN: ${{ github.token }}
          PKG_NAME: ${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title']}}
        run: |
          gh extension install nicovince/gh-container
          gh container versions ${PKG_NAME}
